CREATE DATABASE IF NOT EXISTS PicShare;
USE PicShare;

DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS entries;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(512) NOT NULL,
    name VARCHAR(100),
    avatar VARCHAR(100),
    active BOOLEAN DEFAULT false,
    role ENUM("admin", "normal") DEFAULT "normal" NOT NULL,
    regCode CHAR(36),
    deleted BOOLEAN DEFAULT false,
    lastAuthUpdate DATETIME
);

CREATE TABLE entries (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    place VARCHAR(100) NOT NULL,
    description VARCHAR(250),
    comment TEXT,
    likes INT UNSIGNED DEFAULT 0, 
    user_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE photos (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    photo VARCHAR(100) NOT NULL,
    entry_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (entry_id) REFERENCES entries(id)
);